# nclient = new NominalClient("troia-web-test-1360763539397-760808356804")
# console.log nclient.ping()
# console.log nclient.exists()
# console.log nclient.collect_predicted_labels(() -> console.log nclient.predicted_labels)

cclient = new App.ContinuousClient("test_id")
console.log "ping", cclient.ping()
# if not cclient.exists()
#     cclient.create(() -> console.log cclient.exists())
# console.log cclient.post_assigns([['worker1', 'url1', 2], ['worker1', 'url2', 1]], () ->)
# console.log cclient.post_gold_labels([['url1', 3, 1]], () ->)
